// Starting the persona bootstrap from the cockpit.
//
// The bootstrap is a Claude Code skill, not daemon code, and that is not an
// oversight to route around: it enumerates DM partners and mail correspondents
// through MCP, reads five years of history in chunks with a running extraction
// sheet, and STOPS in the middle to have the user confirm the ranked contact
// list. The cockpit can do none of that. So the button does not run the job —
// it starts the session that runs it, with the invocation already typed.
//
// Interactive on purpose, twice over: an MCP server that needs authorizing
// cannot complete OAuth in a headless run, and the confirmation step has
// nobody to answer it. `claude "<prompt>"` opens a normal session with the
// first message pre-filled, so the user still types nothing.
//
// It launches via a generated .command file rather than osascript. The prompt
// would otherwise be a shell string inside an AppleScript string inside a
// shell argument, and every layer of that nesting is a quoting bug waiting to
// happen with a contact key in it.

import { chmodSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { loadProgress } from "../io/bootstrap-progress.js";
import { progressSummary, type ContactStatus } from "../core/bootstrap.js";
import { REPO_ROOT } from "./updater.js";

export interface BootstrapRequest {
  /** `top:N`, `all`, or a comma-separated key list — the skill's own vocabulary. */
  contacts: string;
  historyYears: number;
  /** Count and rank only. Reads nothing else, writes no persona, spends no drafting tokens. */
  dryRun: boolean;
}

export class InvalidBootstrapRequest extends Error {}

// Everything here ends up inside a generated shell script, so it is validated
// as a whitelist rather than escaped. A contact key is [A-Za-z0-9._-] in this
// codebase; anything else is a bad request, not something to quote around.
export function validateRequest(raw: Partial<BootstrapRequest>): BootstrapRequest {
  const contacts = String(raw.contacts ?? "top:20").trim();
  const ok =
    /^top:\d{1,3}$/.test(contacts) ||
    contacts === "all" ||
    /^[A-Za-z0-9._-]+(,[A-Za-z0-9._-]+)*$/.test(contacts);
  if (!ok) throw new InvalidBootstrapRequest(`unrecognized contacts selector: ${contacts}`);

  const years = Number(raw.historyYears ?? 5);
  if (!Number.isInteger(years) || years < 1 || years > 20) {
    throw new InvalidBootstrapRequest("historyYears must be a whole number of years, 1 to 20");
  }
  return { contacts, historyYears: years, dryRun: raw.dryRun === true };
}

export function bootstrapPrompt(req: BootstrapRequest): string {
  return [
    "bootstrap personas",
    `--contacts ${req.contacts}`,
    `--history-years ${req.historyYears}`,
    req.dryRun ? "--dry-run" : "",
  ]
    .filter(Boolean)
    .join(" ");
}

export function launcherPathFor(statePath: string): string {
  return join(dirname(statePath), "bootstrap-launch.command");
}

/**
 * Write the launcher and open it. Returns the prompt that was handed over, so
 * the UI can show exactly what is about to run — a button that starts a job
 * this long should not be vague about what it started.
 */
export function startPersonaBootstrap(
  statePath: string,
  req: BootstrapRequest,
  openFn: (file: string, args: string[]) => void,
): { prompt: string; launcher: string } {
  const prompt = bootstrapPrompt(req);
  const launcher = launcherPathFor(statePath);
  writeFileSync(
    launcher,
    [
      "#!/bin/bash",
      "# Generated by the cockpit. Safe to delete.",
      `cd ${JSON.stringify(REPO_ROOT)} || exit 1`,
      `exec claude ${JSON.stringify(prompt)}`,
      "",
    ].join("\n"),
    "utf8",
  );
  chmodSync(launcher, 0o755);
  openFn("open", [launcher]);
  return { prompt, launcher };
}

export interface BootstrapState {
  /** Absent until a run has initialized its progress ledger. */
  started: boolean;
  counts: Record<ContactStatus, number>;
  total: number;
}

// The skill writes state/bootstrap-progress.json as it goes, so the cockpit
// can report progress without being in the loop at all.
export function bootstrapState(statePath: string): BootstrapState {
  const p = loadProgress(join(dirname(statePath), "bootstrap-progress.json"));
  if (!p) return { started: false, counts: { pending: 0, staged: 0, promoted: 0, failed: 0 }, total: 0 };
  const counts = progressSummary(p);
  return { started: true, counts, total: Object.values(counts).reduce((a, b) => a + b, 0) };
}
